x-gpu-runtime: &gpu-runtime
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

services:
  dataset-generate:
    <<: *gpu-runtime
  model-train:
    <<: *gpu-runtime
  baseline:
    <<: *gpu-runtime
  rl:
    <<: *gpu-runtime
  nmpc:
    <<: *gpu-runtime
