import os

import numpy as np
import rospy


def _as_bool(value):
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in ("1", "true", "yes", "on")
    return bool(value)


def default_nmpc_params():
    return {
        "hidden_size": 128,
        "hidden_layers": 4,
        "nn_input_dim": 3,
        "nn_output_dim": 4,
        "nn_yaw_harmonics": 4,
        "nn_include_alignment_features": True,
        "nn_output_temperature": 0.4,
        "nn_threshold": 5.0,
        "nn_gate_slope": 10.0,
        "model_device": "cuda",
        "nn_model_dir": "/models/nmpc/fog/yaw_enriched/5m",
        "nn_model_path": "",
        "nn_output_labels": [
            "raw_raw", "raw_ripe", "ripe_raw", "ripe_ripe",
        ],
        "mpc_horizon": 3,
        "dt": 0.25,
        "state_dim": 3,
        "control_dim": 3,
        "optimizer_state_dim": 6,
        "num_target_trees": 1,
        "num_obstacle_trees": 5,
        "sim_steps": 1200,
        "belief_update_period": 1,
        "solver_failure_limit": 5,
        "velocity_estimate_alpha": 0.6,
        "observation_decision_margin": 0.05,
        "belief_tracking_threshold": 0.9975245006578829,
        "tree_entropy_threshold": 0.025,
        "observation_range": 5.0,
        "active_target_count": 1,
        "active_obstacle_count": 5,
        "max_experiment_steps": 1200,
        "initial_pose_margin": 1.5,
        "initial_pose_sleep": 1.5,
        "wait_sleep": 0.05,
        "loop_extra_sleep": 0.1,
        "field_margin": 3.0,
        "max_heading_abs": 3.0 * np.pi,
        "max_velocity": 1.75,
        "max_yaw_velocity": np.pi / 4.0,
        "max_accel_xy": 1.0,
        "max_accel_yaw": np.pi / 2.0,
        "safe_distance": 1.5,
        "movement_weight": 5e-3,
        "yaw_movement_weight": 5e-3,
        "acceleration_regularization_weight": 1e-4,
        "information_gain_weight": 1.5,
        "information_discount": 0.85,
        "entropy_time_pressure_weight": 0.5,
        "exploration_weight": 0.25,
        "exploration_sigma": 5.0,
        "attraction_weight": 1.0,
        "camera_facing_weight": 2.0,
        "camera_yaw_offset": 0.0,
        "camera_activation_sigma": 5.0,
        "observation_standoff": 4.0,
        "observation_standoff_weight": 1.0,
        "running_camera_facing_weight": 1.0,
        "running_observation_standoff_weight": 0.25,
        "orbit_velocity_weight": 0.25,
        "ipopt": {
            "tol": 1e-6,
            "warm_start_init_point": "yes",
            "print_level": 0,
            "sb": "no",
            "warm_start_bound_push": 1e-8,
            "warm_start_mult_bound_push": 1e-8,
            "mu_init": 1e-5,
            "bound_relax_factor": 1e-9,
            "hessian_approximation": "limited-memory",
            "mu_strategy": "monotone",
            "acceptable_tol": 5e-2,
            "acceptable_iter": 3,
            "max_iter": 30,
            "max_cpu_time": 0.18,
        },
        "map_frame": "map",
        "base_frame": "drone_base_link",
        "tree_scores_topic": "tree_scores",
        "cmd_pose_topic": "cmd/pose",
        "cmd_pose_queue_size": 1,
        "tree_scores_queue_size": 1,
        "predicted_path_topic": "predicted_path",
        "tree_markers_topic": "tree_markers",
        "publish_predicted_path": True,
        "publish_tree_markers": True,
        "visualization_publish_period": 5,
        "tree_service": "/obj_pose_srv",
        "run_dir": "/runs/nmpc_runs",
        "wandb_enabled": False,
        "wandb_project": "semantic_mpc",
        "wandb_entity": "",
        "wandb_mode": "offline",
        "wandb_log_every_steps": 4,
        "num_runs": 1,
        "run_index_offset": 0,
        "seed": 1,
        "random_initial_state": True,
        "start_pose": None,
        "initial_corner_margin": 2.0,
        "mower_heading": "N",
        "mower_heading_random": False,
        "initial_pose_timeout": 15.0,
        "initial_pose_tolerance": 0.15,
        "initial_heading_tolerance": 0.2,
        "initial_pose_publish_period": 0.1,
        "measurement_period": 0.25,
        "tree_velocity_radius": 5.0,
    }


def load_semantic_mpc_params():
    names = [
        "hidden_size",
        "hidden_layers",
        "nn_input_dim",
        "nn_output_dim",
        "nn_yaw_harmonics",
        "nn_include_alignment_features",
        "nn_output_temperature",
        "nn_threshold",
        "nn_gate_slope",
        "model_device",
        "nn_model_dir",
        "nn_model_path",
        "nn_output_labels",
        "mpc_horizon",
        "dt",
        "state_dim",
        "control_dim",
        "optimizer_state_dim",
        "num_target_trees",
        "num_obstacle_trees",
        "sim_steps",
        "belief_update_period",
        "solver_failure_limit",
        "belief_tracking_threshold",
        "tree_entropy_threshold",
        "observation_range",
        "active_target_count",
        "active_obstacle_count",
        "max_experiment_steps",
        "initial_pose_margin",
        "initial_pose_sleep",
        "wait_sleep",
        "loop_extra_sleep",
        "field_margin",
        "max_heading_abs",
        "max_velocity",
        "max_yaw_velocity",
        "max_accel_xy",
        "max_accel_yaw",
        "safe_distance",
        "movement_weight",
        "yaw_movement_weight",
        "acceleration_regularization_weight",
        "information_gain_weight",
        "information_discount",
        "entropy_time_pressure_weight",
        "exploration_weight",
        "exploration_sigma",
        "attraction_weight",
        "camera_facing_weight",
        "camera_yaw_offset",
        "camera_activation_sigma",
        "observation_standoff",
        "observation_standoff_weight",
        "running_camera_facing_weight",
        "running_observation_standoff_weight",
        "orbit_velocity_weight",
        "ipopt",
        "map_frame",
        "base_frame",
        "tree_scores_topic",
        "cmd_pose_topic",
        "cmd_pose_queue_size",
        "tree_scores_queue_size",
        "predicted_path_topic",
        "tree_markers_topic",
        "publish_predicted_path",
        "publish_tree_markers",
        "visualization_publish_period",
        "tree_service",
        "run_dir",
        "wandb_enabled",
        "wandb_project",
        "wandb_entity",
        "wandb_mode",
        "wandb_log_every_steps",
        "num_runs",
        "run_index_offset",
        "seed",
        "random_initial_state",
        "start_pose",
        "initial_corner_margin",
        "mower_heading",
        "mower_heading_random",
        "initial_pose_timeout",
        "initial_pose_tolerance",
        "initial_heading_tolerance",
        "initial_pose_publish_period",
        "measurement_period",
        "tree_velocity_radius",
        "velocity_estimate_alpha",
        "observation_decision_margin",
    ]
    loaded = {}
    for name in names:
        if rospy.has_param("~" + name):
            loaded[name] = rospy.get_param("~" + name)

    int_names = {
        "hidden_size",
        "hidden_layers",
        "nn_input_dim",
        "nn_output_dim",
        "nn_yaw_harmonics",
        "mpc_horizon",
        "state_dim",
        "control_dim",
        "optimizer_state_dim",
        "num_target_trees",
        "num_obstacle_trees",
        "sim_steps",
        "belief_update_period",
        "solver_failure_limit",
        "cmd_pose_queue_size",
        "tree_scores_queue_size",
        "visualization_publish_period",
        "num_runs",
        "run_index_offset",
        "seed",
        "active_target_count",
        "active_obstacle_count",
        "max_experiment_steps",
        "wandb_log_every_steps",
    }
    bool_names = {
        "publish_predicted_path",
        "publish_tree_markers",
        "random_initial_state",
        "mower_heading_random",
        "wandb_enabled",
        "nn_include_alignment_features",
    }
    float_names = {
        "nn_threshold",
        "nn_gate_slope",
        "nn_output_temperature",
        "dt",
        "belief_tracking_threshold",
        "tree_entropy_threshold",
        "observation_range",
        "initial_pose_margin",
        "initial_pose_sleep",
        "wait_sleep",
        "loop_extra_sleep",
        "field_margin",
        "max_heading_abs",
        "max_velocity",
        "max_yaw_velocity",
        "max_accel_xy",
        "max_accel_yaw",
        "safe_distance",
        "movement_weight",
        "yaw_movement_weight",
        "acceleration_regularization_weight",
        "information_gain_weight",
        "information_discount",
        "entropy_time_pressure_weight",
        "exploration_weight",
        "exploration_sigma",
        "attraction_weight",
        "camera_facing_weight",
        "camera_yaw_offset",
        "camera_activation_sigma",
        "observation_standoff",
        "observation_standoff_weight",
        "running_camera_facing_weight",
        "running_observation_standoff_weight",
        "orbit_velocity_weight",
        "initial_corner_margin",
        "initial_pose_timeout",
        "initial_pose_tolerance",
        "initial_heading_tolerance",
        "initial_pose_publish_period",
        "measurement_period",
        "tree_velocity_radius",
        "velocity_estimate_alpha",
        "observation_decision_margin",
    }
    for name in int_names.intersection(loaded):
        loaded[name] = int(loaded[name])
    for name in float_names.intersection(loaded):
        loaded[name] = float(loaded[name])
    for name in bool_names.intersection(loaded):
        loaded[name] = _as_bool(loaded[name])
    return loaded
